name: Update Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-root

      - name: Update data
        run: poetry run python main.py
