name: Update Data

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-root

      - name: Update data
        run: |
          git config user.name 'GitHub Runner'
          poetry run python main.py
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_REPOSITORY: ${{ secrets.GIT_REPOSITORY }}
          GIT_PROJECT_ID: ${{ secrets.GIT_PROJECT_ID }}
          FOLDER: ExcelBinOutput
          LANG_FOLDER: TextMap
          AVATAR: AvatarExcelConfigData.json
          COSTUME: AvatarCostumeExcelConfigData.json
          SKILLDEPOT: AvatarSkillDepotExcelConfigData.json
          SKILLS: AvatarSkillExcelConfigData.json
          TALENTS: AvatarTalentExcelConfigData.json
          ARTIFACTS: ReliquaryExcelConfigData.json
          WEAPONS: WeaponExcelConfigData.json
          ARTIFACTS_SETS: EquipAffixExcelConfigData.json
          FIGHT_PROPS: ManualTextMapConfigData.json
          PROPS_MAP: ProudSkillExcelConfigData.json
          NAMECARDS: MaterialExcelConfigData.json
          ARTIFACT_PROPS_MAIN: ReliquaryMainPropExcelConfigData.json
          ARTIFACT_PROPS_SUB: ReliquaryAffixExcelConfigData.json
